### ISSUE TITLE
HDR config for ffmpeg plugin?

### ISSUE THREAD

**Issue by pryg-skok** [intel/SVT-HEVC#104]
Have you got any plans for it? 
Anyway can you help to configure it in current version of plugin?

**Comment by jsunintel** [comment]
Which HDR?

**Comment by pryg-skok** [comment]
Sorry, I thought there no place for misunderstanding. Of course I mean High Dynamic Range metainformation forwarding from encoder input to output. There is option in encoder, but I can't specify it via ffmpeg plugin.

**Comment by tianjunwork** [comment]
Hi @jsunintel is this option going to be exposed to ffmpeg plugin?

**Comment by jsunintel** [comment]
> 
> 
> Hi @jsunintel is this option going to be exposed to ffmpeg plugin?

Will consider it, but being quite occupied right now.
