### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by idxa** [intel/SVT-HEVC#11]
hi, my enviroment is centos6.9, when running build.sh, show the following info which failed to get the executable file. Could anyone have a look, thanks!  

[100%] Linking C executable HevcEncoderApp
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `EbPictureBufferDescCtor'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `memoryMapIndex'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `memoryMap'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `totalLibMemory'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `ASM_TYPES'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `libMutexCount'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `libSemaphoreCount'
/home/workspace/tmp/SVT-HEVC-master/Source/../Bin/Release/libHevcEncoder.so: undefined reference to `libMallocCount'
collect2: error: ld returned 1 exit status
make[3]: *** [App/HevcEncoderApp] Error 1
make[2]: *** [App/CMakeFiles/HevcEncoderApp.dir/all] Error 2
make[1]: *** [App/CMakeFiles/HevcEncoderApp.dir/rule] Error 2
make: *** [HevcEncoderApp] Error 2
cp: cannot stat `App/HevcEncoderApp': No such file or directory

**Comment by tianjunwork** [comment]
@idxa Thx for your question. 
For Linux* Operating Systems (64-bit), SVT is tested and validated on:
Ubuntu* 16.04 Desktop LTS
Ubuntu* 16.04 Server LTS
Ubuntu* 18.04 Desktop LTS
Ubuntu* 18.04 Server LTS
It is not guaranteed on CentOS.

Please check if your tools follow:
GCC 5.4.0 or later
CMake 3.5.1 or later
YASM Assembler version 1.2.0 or later

**Comment by idxa** [comment]
In order to compile svtEncoder，I updated gcc to 6.1.0, cmake to 3.6.1, yasm to 1.3.0 and binutils to 2.29.  It looks like that building failed in the last step which link to get a execute file,  maybe some problem such as extern "C"...

**Comment by tianjunwork** [comment]
@idxa Since you post another question about video quality, did you get it built on CentOS?

**Comment by hassount** [comment]
@mypopydev 
Thank you for your feedback, we will take such into consideration.

**Comment by tianjunwork** [comment]
@idxa CentOS is supported on master. We will announce it officially soon. You can try it out. Thx for your input.
