### ISSUE TITLE
Distorted output image with 540x960 input file 

### ISSUE THREAD

**Issue by idxa** [intel/SVT-HEVC#12]
cmd:  ../bin/HevcEncoderApp -c ../bin/Sample.cfg -i clip2_540x960_25_org.yuv -w 540 -h 960 -n 200 -rc 0 -q 26 -fps 25  -b test_new.265，result is distorted like the following：
![Uploading image.png…](http://s3.ivideo.sina.com.cn/test.jpg)

source file and output test_new.265 can download from https://pan.baidu.com/s/1jEBzesyQ4-FEjyhITjvexA

**Comment by tianjunwork** [comment]
@idxa Thx for the feedback and providing the files.
Will try to reproduce and get back to you.

**Comment by tnti** [comment]
多嘴说一句 以后github上的样例啥的最好找国外的盘传...
Dropbox、MEGA、Google Drive、OneDrive、iCloud这一类的 毕竟百度盘在国外是不怎么好下载的。
The above content has nothing to do with the problem.

**Comment by hassount** [comment]
This issue should be addressed in the head of the master branch. Please let us know if you still see any issues with this.
