### ISSUE TITLE
How to build static libSvtHevcEnc.so?

### ISSUE THREAD

**Issue by pryg-skok** [intel/SVT-HEVC#128]
Hi, could you please provide static target for libSvtHevcEnc? It's easier for deploying.
I have tried to manually fix Source/Lib/Codec/CMakeLists.txt but then its failed to Built target SvtHevcEncSimpleApp:
```
[100%] Linking C executable ../../../Bin/Release/SvtHevcEncApp
[100%] Built target SvtHevcEncSimpleApp
EbEncHandle.c.o (symbol from plugin): In function `EbOutputBufferHeaderCtor':
(.text+0x0): multiple definition of `AllocateFrameBuffer'
CMakeFiles/SvtHevcEncApp.dir/EbAppContext.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `EbOutputBufferHeaderCtor':
(.text+0x0): multiple definition of `invoke_safe_str_constraint_handler'
CMakeFiles/SvtHevcEncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `EbOutputBufferHeaderCtor':
(.text+0x0): multiple definition of `ignore_handler_s'
CMakeFiles/SvtHevcEncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `EbOutputBufferHeaderCtor':
(.text+0x0): multiple definition of `strncpy_ss'
CMakeFiles/SvtHevcEncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `EbOutputBufferHeaderCtor':
(.text+0x0): multiple definition of `strcpy_ss'
CMakeFiles/SvtHevcEncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbEncHandle.c.o (symbol from plugin): In function `EbOutputBufferHeaderCtor':
(.text+0x0): multiple definition of `strnlen_ss'
CMakeFiles/SvtHevcEncApp.dir/EbAppFifo.c.o (symbol from plugin):(.text+0x0): first defined here
EbUtility.c.o (symbol from plugin): In function `ZOrderIncrement':
(.text+0x0): multiple definition of `EbStartTime'
CMakeFiles/SvtHevcEncApp.dir/EbTime.c.o (symbol from plugin):(.text+0x0): first defined here
EbUtility.c.o (symbol from plugin): In function `ZOrderIncrement':
(.text+0x0): multiple definition of `EbFinishTime'
CMakeFiles/SvtHevcEncApp.dir/EbTime.c.o (symbol from plugin):(.text+0x0): first defined here
EbUtility.c.o (symbol from plugin): In function `ZOrderIncrement':
(.text+0x0): multiple definition of `EbComputeOverallElapsedTime'
CMakeFiles/SvtHevcEncApp.dir/EbTime.c.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Source/App/CMakeFiles/SvtHevcEncApp.dir/build.make:230: recipe for target '../Bin/Release/SvtHevcEncApp' failed
make[2]: *** [../Bin/Release/SvtHevcEncApp] Error 1
CMakeFiles/Makefile2:457: recipe for target 'Source/App/CMakeFiles/SvtHevcEncApp.dir/all' failed
make[1]: *** [Source/App/CMakeFiles/SvtHevcEncApp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tianjunwork** [comment]
@pryg-skok you can build *.a and simple app without any issue. But you failed to build SvtHevcEncApp.
There is no plan to support both static/dynamic library build. So here is the receipt to build SvtHevcEncApp to unblock you:
diff --git a/Source/App/CMakeLists.txt b/Source/App/CMakeLists.txt
index 7256f47..aaf35ac 100644
--- a/Source/App/CMakeLists.txt
+++ b/Source/App/CMakeLists.txt
@@ -16,7 +16,6 @@ include_directories (${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)
 add_executable (SvtHevcEncApp
     EbAppConfig.c
     EbAppContext.c
-    EbAppFifo.c
     EbAppMain.c
     EbAppProcessCmd.c
     EbTime.c
@@ -45,4 +44,4 @@ if (MSVC OR MSYS OR MINGW OR WIN32)
                            SvtHevcEnc)
 endif()

-install(TARGETS SvtHevcEncApp RUNTIME DESTINATION bin)
\ No newline at end of file
+install(TARGETS SvtHevcEncApp RUNTIME DESTINATION bin)
diff --git a/Source/App/EbAppContext.c b/Source/App/EbAppContext.c
index 3ec9bc0..8df47e7 100644
--- a/Source/App/EbAppContext.c
+++ b/Source/App/EbAppContext.c
@@ -241,7 +241,7 @@ EB_ERRORTYPE CopyConfigurationParameters(
 }


-EB_ERRORTYPE AllocateFrameBuffer(
+static EB_ERRORTYPE AllocateFrameBuffer(
     EbConfig_t          *config,
     uint8_t               *pBuffer)
 {
diff --git a/Source/App/EbTime.c b/Source/App/EbTime.c
index 61c91cb..4220dbf 100644
--- a/Source/App/EbTime.c
+++ b/Source/App/EbTime.c
@@ -22,7 +22,7 @@
 #error OS/Platform not supported.
 #endif

-void EbStartTime(
+static void EbStartTime(
     uint64_t *Startseconds,
     uint64_t *Startuseconds)
 {
@@ -42,7 +42,7 @@ void EbStartTime(

 }

-void EbFinishTime(
+static void EbFinishTime(
     uint64_t *Finishseconds,
     uint64_t *Finishuseconds)
 {
@@ -61,7 +61,7 @@ void EbFinishTime(
 #endif

 }
-void EbComputeOverallElapsedTime(
+static void EbComputeOverallElapsedTime(
     uint64_t Startseconds,
     uint64_t Startuseconds,
     uint64_t Finishseconds,
diff --git a/Source/Lib/Codec/CMakeLists.txt b/Source/Lib/Codec/CMakeLists.txt
index 527630c..55032e4 100644
--- a/Source/Lib/Codec/CMakeLists.txt
+++ b/Source/Lib/Codec/CMakeLists.txt
@@ -24,7 +24,7 @@ set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}
 set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)

 # Encoder Lib Source Files
-add_library(SvtHevcEnc SHARED
+add_library(SvtHevcEnc
     EbAdaptiveMotionVectorPrediction.h
     EbAvailability.h
     EbAvcStyleMcp.h

**Comment by pryg-skok** [comment]
Thanks! But patch cannot be applied on last commit: 4fdfae87fe0a97c56e99f5d4e505ddf69f02bcc6
And I've tried several commits before it - same thing.
Fixed version if you need it:
```
diff --git a/Source/App/CMakeLists.txt b/Source/App/CMakeLists.txt
index 7256f47..30ba30d 100644
--- a/Source/App/CMakeLists.txt
+++ b/Source/App/CMakeLists.txt
@@ -16,7 +16,6 @@ include_directories (${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)
 add_executable (SvtHevcEncApp
     EbAppConfig.c
     EbAppContext.c
-    EbAppFifo.c
     EbAppMain.c
     EbAppProcessCmd.c
     EbTime.c
@@ -44,5 +43,3 @@ if (MSVC OR MSYS OR MINGW OR WIN32)
 	target_link_libraries (SvtHevcEncApp
                            SvtHevcEnc)
 endif()
-
-install(TARGETS SvtHevcEncApp RUNTIME DESTINATION bin)
\ No newline at end of file
diff --git a/Source/App/EbAppContext.c b/Source/App/EbAppContext.c
index b98f5b0..e74ca8f 100644
--- a/Source/App/EbAppContext.c
+++ b/Source/App/EbAppContext.c
@@ -246,7 +246,7 @@ EB_ERRORTYPE CopyConfigurationParameters(
 }
 
 
-EB_ERRORTYPE AllocateFrameBuffer(
+static EB_ERRORTYPE AllocateFrameBuffer(
     EbConfig_t          *config,
     uint8_t               *pBuffer)
 {
diff --git a/Source/App/EbTime.c b/Source/App/EbTime.c
index 61c91cb..4220dbf 100644
--- a/Source/App/EbTime.c
+++ b/Source/App/EbTime.c
@@ -22,7 +22,7 @@
 #error OS/Platform not supported.
 #endif
 
-void EbStartTime(
+static void EbStartTime(
     uint64_t *Startseconds,
     uint64_t *Startuseconds)
 {
@@ -42,7 +42,7 @@ void EbStartTime(
 
 }
 
-void EbFinishTime(
+static void EbFinishTime(
     uint64_t *Finishseconds,
     uint64_t *Finishuseconds)
 {
@@ -61,7 +61,7 @@ void EbFinishTime(
 #endif
 
 }
-void EbComputeOverallElapsedTime(
+static void EbComputeOverallElapsedTime(
     uint64_t Startseconds,
     uint64_t Startuseconds,
     uint64_t Finishseconds,
diff --git a/Source/Lib/Codec/CMakeLists.txt b/Source/Lib/Codec/CMakeLists.txt
index 527630c..55032e4 100644
--- a/Source/Lib/Codec/CMakeLists.txt
+++ b/Source/Lib/Codec/CMakeLists.txt
@@ -24,7 +24,7 @@ set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}
 set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)
 
 # Encoder Lib Source Files
-add_library(SvtHevcEnc SHARED  
+add_library(SvtHevcEnc
     EbAdaptiveMotionVectorPrediction.h
     EbAvailability.h
     EbAvcStyleMcp.h
```
Anyway thanks - it seems it's worked :)

**Comment by pryg-skok** [comment]
Maybe it's better to include cmake configure option for such build.
