### ISSUE TITLE
[FFmpeg plugin] didn't handle PTS/DTS in SVT-HEVC FFmpeg plugin

### ISSUE THREAD

**Issue by mypopydev** [intel/SVT-HEVC#19]
After apply the FFmpeg plugin patch to FFmpeg, then run the transcode with the command:

 ./ffmpeg -i ~/Videos/skyfall2-trailer.mp4 -an -c:v libsvt_hevc test_svt.mp4

get the message like: 

~~~
[mp4 @ 0x556f3d808940] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mp4 @ 0x556f3d808940] Encoder did not produce proper pts, making some up.
~~~

I think the plugin didn't handle the DTS/PTS.

**Comment by tianjunwork** [comment]
@mypopydev thank you for your attention to the detailed message that helps us find what is missing in the plugin. I wonder if you have time to fix it? Thanks in advance.

**Comment by hassount** [comment]
@mypopydev @tianjunwork 
I apologize for the late response on this. actually this work is in progress and both the library and the plugin will be updated accordingly.

**Comment by hassount** [comment]
this issue has been handled in the new_api branch

**Comment by mypopydev** [comment]
@hassount Will close this issue, now new_api branch have fix this issue.
