### ISSUE TITLE
How many physical cores is the best  to svt-hevc?

### ISSUE THREAD

**Issue by zhongyizengzy** [intel/SVT-HEVC#2]
Could you give a config item like --threads or give a theoretical boundary about the cores?I don't know how many physical cores is suitable to svt-hevc。

**Comment by tianjunwork** [comment]
The SVT-HEVC Encoder doesn't limit how many cores it runs on.  It features density-quality tradeoffs. CPU requirements depends on your usage.  For real time encoding, the profiling data is below.  For scenario that is not latency critical, you can have lower end of Xeon CPU.
As you can find in the README file: 
The encoder has been optimized to achieve excellent performance levels using 13 density-quality presets on a system with a dual Intel® Xeon® Scalable CPU targeting:
Real-time encoding of up to one 8Kp60/10-bit streams on the Platinum 8180 with M11 in the subjective quality mode
Real-time encoding of up to two 8Kp50/10-bit streams on the Platinum 8180 with M12 in the subjective quality mode
Real-time encoding of up to four 4Kp60/10-bit streams on the Gold 6148 with M12 in the subjective quality mode
Real-time encoding of up to six 4Kp60/10-bit streams on the Platinum 8180 with M12 in the subjective quality mode
Just for your info, if you run multi-channel simultaneous encode on a a dual socket system, to achieve the best performance, please follow the "Command line BKC" in user guide.
