### ISSUE TITLE
VBR CRASH?

### ISSUE THREAD

**Issue by zhongyizengzy** [intel/SVT-HEVC#3]
cmd:
HevcEncoderApp -i Transcode/3mins/yuv/电视剧_室内_3mins.yuv -w 1920 -h 1080 -intra-period 249 -irefresh-type 2 -rc 1  -vid-info 1 -tune 0  -tbr 4000000 -profile 1 -level 4.1 -tier 0  -fps 30 -encMode 9 -hierarchical-levels 3  -b svt-265/电视剧_室内_3mins.h265
-------------------------------------
SVT-HEVC Encoder v1.2.0
Platform:   64 bit
Compiler: GCC
APP Build date: Sep 29 2018 09:26:14
LIB Build date: Sep 29 2018 09:25:39
-------------------------------------
Number of cores available: 32
Encoding      1656Segmentation fault

I've tested three sequences, occurs “Segmentation fault”

System Config:
Linux version 4.4.0-117-generic (buildd@lgw01-amd64-029) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #141-Ubuntu SMP Tue Mar 13 11:58:07 UTC 2018

**Comment by hassount** [comment]
@zhongyizengzy 
Thank you for reporting the issue. we will work on reproducing this on our end. that said have you seen this issue with a clip that is public that you can point us to ?

**Comment by zhongyizengzy** [comment]
> @zhongyizengzy
> Thank you for reporting the issue. we will work on reproducing this on our end. that said have you seen this issue with a clip that is public that you can point us to ?

Sorry,the clip is protected by copyright.

**Comment by hassount** [comment]
No problem, we were able to reproduce the issue on our side and we are working on addressing it as soon as possible. 

in the meantime, to get your tests running you could change the following definition in "EbEncodeContext.h" to be > the number of frames in your clips:
#define HIGH_LEVEL_RATE_CONTROL_HISTOGRAM_QUEUE_MAX_DEPTH   2048
so assuming you're running 3 min videos, multiplying the above by 4 should get the crash away.
that is:
#define HIGH_LEVEL_RATE_CONTROL_HISTOGRAM_QUEUE_MAX_DEPTH   (2048 << 2)

**Comment by hassount** [comment]
@zhongyizengzy 
A fix has been developed for this issue and is being validated, please refer to #5

**Comment by hassount** [comment]
Addressed in #5
