### ISSUE TITLE
Incorrect frame rate of the output video

### ISSUE THREAD

**Issue by Hrisi** [intel/SVT-HEVC#34]
I encode a 4K video by setting the frame rate and the number of frames as follows:

_ffmpeg -i "input" -nostdin -f rawvideo -pix_fmt yuv420p - | ./HevcEncoderApp -i stdin -fps 30 -n 60 -w 3840 -h 2048 -b output.bin_

The encoder finishes successfully and according to the summary at the end, 60 frames are encoded and the frame rate is **30fps**:

_SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames		Frame Rate		Byte Count		Bitrate
          60		30.00 fps		    963170		3852.68 kbps_

However, when I check the frame rate of the output binary video (ffprobe), I get **25fps**. The duration and the bit-rate of the output video cannot be estimated because of  "_missing picture in access unit_". I tested the encoder with different videos (in terms of resolution and frame rate) and the software always produces output videos with 25fps.

I run the encoder on Ubuntu 16.04 with 2 cores.

**Comment by hassount** [comment]
@Hrisi 
Thank you for your feedback. 
The frame rate is sent as part of the vui structure which is disabled by default. To enable encoding the vui, you'd need to set -vid-info to 1

**Comment by Hrisi** [comment]
@hassount 
Thank you very much for the reply! Setting -vid-info to 1 fixed the issue!
