### ISSUE TITLE
Artifacts in the output 265 video

### ISSUE THREAD

**Issue by miaoqiz** [intel/SVT-HEVC#40]
Hi,

I used the tool on "Ubuntu" to encode a 2K/HDR video with the following command:

**sudo HevcEncoderApp -i input.raw -b ouput.265 -w 1920 -h 1080 -fps 23.976 -bit-depth 10 -tune 0 -rc 1 -tbr 15000000 -encMode 0 -level 6.2 -tier 1**

The encoding was finished; however, a lot of artifacts appears when playing the output 265 file with different players. 

There are lots of bad blocks and noises here and there in the frames and the artifacts come to its peak especially when there is a big scene difference. Would you mind taking a look at the command and providing some feedback on how to fix it?

Also, processing a 4K video tends to freeze the machine (4 cores). Is there a way to specify number of cores to be used?

Thanks a lot!

MQ

![intel_hevc_screenshot](https://user-images.githubusercontent.com/20649192/49974261-38e47280-feed-11e8-9095-3c92de984bd7.png)

**Comment by hassount** [comment]
@miaoqiz 
Thank you for your feedback. 
Would you be able to upload the content for us, or point us to where we can download this content ? 

As for limiting the usage: you can use:

sudo **taskset 0x3** HevcEncoderApp -i input.raw -b ouput.265 -w 1920 -h 1080 -fps 23.976 -bit-depth 10 -tune 0 -rc 1 -tbr 15000000 -encMode 0 -level 6.2 -tier 1
that will limit the core usage to 2 cores only

**Comment by miaoqiz** [comment]
@hassount 

Thanks for the suggestion!

It is likely that the artifacts appear when encoding 10-bit YUV video. Can you test with this kind of materials on your side?

Thanks!

**Comment by miaoqiz** [comment]
@tianjunwork Hi, thanks for the quick feedback! Can you try this:

1. Convert a sequence of source images to 10-bit 420 YUV file;
2. Encode with Intel SVT-HEVC

I did some tests, if I convert the sequence to 8-bit 420 YUV file in the first step, then things looks normal in the encoded 265 video; however, the artifacts will show up if the input is 10-bit 420 YUV / raw file. It happened to both SDR and HDR source.

Thanks!

**Comment by miaoqiz** [comment]
I have played both the 420 YUV file the 265 file with two robust media players.

**Comment by tianjunwork** [comment]
@miaoqiz The 10bits videos we use are from here: https://media.xiph.org/video/derf/.
I am confused. You were saying that you saw no issue regardless of bit-depth with input yuv file or output yuv file (decoded from output.265)? 
If output yuv file is of no issue, could you close this topic?

**Comment by miaoqiz** [comment]
@tianjunwork Sorry for the confusion. The input YUV files are made by me. They have no issues regardless of the bit depth. The encoded 265 videos by Intel SVT-HEVC encoder tend to show the artifacts when it comes to encoding 10-bit YUV420 raw file. We are not decoding anything from 265 files to YUV files. 

Thanks!

**Comment by hassount** [comment]
@miaoqiz 
Can you just send us the yuv (even a few frames from it) ?

**Comment by miaoqiz** [comment]
@hassount Thanks for the quick reply! If possible, would you mind sending me 10 to 20 source frames (16-bit, 12-bit ), I can then convert them into 420 YUV file and send it back to you for testing? 

Thanks

**Comment by tianjunwork** [comment]
@miaoqiz 
You can visit https://media.xiph.org/video/derf/ and download any 1080p video sequence.
Use truncate command to cut the file to get a smaller one that is easier to share with us.

**Comment by miaoqiz** [comment]
Hi, thanks for the link!

By glancing over it, it seems that most of the sources are 8-bit. Have you encoded from a 10-bit YUV/raw file before?

Thanks!

**Comment by tianjunwork** [comment]
@miaoqiz There are 10-bit video in the link. Please look for them.
Yes, we did encode with 10-bit input. As I said earlier, after you get output.265, decode it to yuv back again (ffmpeg -i output.265 10bit.yuv), and playback with a yuv player, the video is fine without any artifacts.

**Comment by miaoqiz** [comment]
Hi, thanks for the quick reply! Appreciate it.

I saw the 10-bit “y4m” videos. The videos may contain headers and frame boundary delimiters. I can still encode a few to see if the artifacts are present. 

Please be aware I have encoded the same YUV sources with multiple HEVC encoders, so far Intel’s encoder shows artifacts when the source is 10 bit. 

As suggested, I created raw files (420 YUV) based on a sequence of still frames (e.g., 16-bit TIFF) from scratch. I could use “ffmpeg” etc, but there could be something else that might change the pixel values if not careful enough in terms of referencing the parameters.

Have you tried encoding 10-bit raw YUV file that only contains image data? If so, what is the recommended command like? Can I stick with mine indicated in the previous threads of discussions?

Thanks!

**Comment by miaoqiz** [comment]
@tianjunwork Thanks for the effort! I appreciate it!

The command that I used is:

sudo taskset 0x3 HevcEncoderApp -i input.raw -b ouput.265 -w 1920 -h 1080 -fps 23.976 -bit-depth 10 -tune 0 -rc 1 -tbr 15000000 -encMode 0 -level 6.2 -tier 1

I will use the suggested "ffmpeg" command to generate YUV420 file. Sorry I cannot share the source file.

**Comment by tianjunwork** [comment]
@miaoqiz I meant could you send me your ffmpeg command to generate yuv file.
Also, I am using the latest source code. If you try, could you use the latest code?

**Comment by miaoqiz** [comment]
@tianjunwork Thanks for letting me know! I wrote my own code to generate YUV420 raw files. The outputs have been tested on various YUV players and they looks fine. 

I will re-built the encoder.

**Comment by tianjunwork** [comment]
@miaoqiz Any update with this issue? If not, could you close it?

**Comment by miaoqiz** [comment]
@tianjunwork Hi, I did not get a chance to experiment with the new version. I can close it for now. If I have time to experiment with it and find new issues, I will re-open it.

Thanks a lot!
