### ISSUE TITLE
Main10 profile encoding failed

### ISSUE THREAD

**Issue by tnti** [intel/SVT-HEVC#49]
An example of the encoding command line is as follows:
"D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.mp4" -pix_fmt p010le -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-HEVC\SvtHevcEncApp" -i stdin -encMode 9 -tune 0 -w 1920 -h 1080 -bit-depth 10 -profile 2 -fps-num 24000 -fps-denom 1001 -q  30 -n 300 -b "%~dpn1_SVT-HEVC.hevc"

You can use any H.264 video file encoding to reproduce the problem.

**Comment by hassount** [comment]
@tnti 
Thank you for your feedback. Can you please elaborate a little more on the failure that happened here ? is it a wrong output? 
SVT-HEVC supports only the yuv420p10le format of a similar compressed format. please refer to sections 3.1 and 3.2 in the [users guide](https://github.com/intel/SVT-HEVC/blob/master/Docs/SVT-HEVC_Encoder_User_Guide.pdf).

**Comment by tnti** [comment]
An example of the encoding command line is as follows:
"D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.avs" -pix_fmt yuv420p10le -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-HEVC\SvtHevcEncApp" -i stdin -encMode 9 -tune 0 -w 1920 -h 1080 -bit-depth 10 -compressed-ten-bit-format 1 -profile 2 -fps-num 24000 -fps-denom 1001 -q 30 -n 300 -b "%~dpn1_SVT-HEVC.hevc"

Turning on the CompressedTenBitFormat option will result in an error in the encoding result.
as the picture shows
![](http://wx2.sinaimg.cn/mw690/7979e806ly1fyor10fxf0j219c0t3n5p.jpg)

Close the CompressedTenBitFormat option and the encoding result is correct.

**Comment by hassount** [comment]
@tnti 
Thank you for the additional information. 
The two command lines you have are the following: 

> "D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.mp4" -pix_fmt p010le -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-HEVC\SvtHevcEncApp" -i stdin -encMode 9 -tune 0 -w 1920 -h 1080 -bit-depth 10 -profile 2 -fps-num 24000 -fps-denom 1001 -q 30 -n 300 -b "%~dpn1_SVT-HEVC.hevc"

and 

> "D:\Encoder\FFMPEG\ffmpeg.exe" -loglevel level+error -i "%~dpn1.avs" -pix_fmt yuv420p10le -strict -1 -f rawvideo -nostdin - | "D:\Encoder\SVT-HEVC\SvtHevcEncApp" -i stdin -encMode 9 -tune 0 -w 1920 -h 1080 -bit-depth 10 -compressed-ten-bit-format 1 -profile 2 -fps-num 24000 -fps-denom 1001 -q 30 -n 300 -b "%~dpn1_SVT-HEVC.hevc"

Does this mean that the first one is working fine? if so, I do not understand where the issue is. 

The compressed-ten-bit-format option assumes the yuv input is in a specific format as shown in section 3 in the users guide. Feeding the yuv in a difference format will certainly cause the behavior you are seeing above.

**Comment by tnti** [comment]
The second command line instruction works fine.
Maybe I should not use compressed-ten-bit-format? @hassount

**Comment by hassount** [comment]
@tnti 
the second command line has compressed-ten-bit-format to be set to 1 and that works? 
basically compressed-ten-bit-format should only be used when the input yuv is in the specific format described in section 3 of the users guide.

**Comment by tnti** [comment]
@hassount 
thank you. 
The above problem occurs when I use compressed-ten-bit-format.
Maybe I don't need to turn this feature on.
