### ISSUE TITLE
Preset 10 not working for Objective VQ mode in FFMPEG

### ISSUE THREAD

**Issue by vasavee** [intel/SVT-HEVC#56]
While using FFMPEG with SVT-HEVC plugin, -preset 10 doesn't work for objective VQ mode. Based on the readme document, 1080p should support upto encMode 10 for both tune 0 and tune 1.
below is the command I am using:
/ffmpeg -i <input.mp4> -c:v libsvt_hevc -tune 1 -preset 10 out.mp4

---------------------------------------------------------------------------------------------------------------
ffmpeg version n4.1-14-gddc2843 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-libsvthevc
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/intel/Downloads/train_dog.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1mp42
    creation_time   : 2009-02-20T00:09:11.000000Z
  Duration: 00:05:01.21, start: 0.000000, bitrate: 628 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2009-02-20T00:09:11.000000Z
      handler_name    : (C) 2007 Google Inc. v08.13.2007.
    Stream #0:1(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 480x320 [SAR 1:1 DAR 3:2], 500 kb/s, 29.97 fps, 29.97 tbr, 29967 tbn, 59934 tbc (default)
    Metadata:
      creation_time   : 2009-02-20T00:09:12.000000Z
      handler_name    : (C) 2007 Google Inc. v08.13.2007.
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> hevc (libsvt_hevc))
  Stream #0:0 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
SVT [version]:  SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :  GCC 6.3.0        64 bit
LIB Build date: Jan  2 2019 15:30:58
-------------------------------------------
Error instance 1: encMode must be [0 - 9] for this resolution
Error instance 1: encMode must be [0 - 9]
[libsvt_hevc @ 0x40110c0] Error setting encoder parameters
*** Error in `./ffmpeg': free(): invalid pointer: 0x0000000004afcdd0 ***

**Comment by ph0b** [comment]
the stream you're trying to encode seem to have a resolution of 480x320, not 1080p, so yes encMode 10 isn't supported with this resolution.
