### ISSUE TITLE
Parameter "-vid-info" not take effect in SVT-HEVC

### ISSUE THREAD

**Issue by liweki** [intel/SVT-HEVC#67]
Hi,
Parameter "-vid-info" doesn't take effect while do encoding with SVT-HEVC.
- Try to use SVT-HEVC version v1.2.0 to encode HEVC bitstreams with parameter "-vid-info" equals to 0 or 1, then use tools to check generated HEVC bitstreams, the value of "vps_timing_info_present_flag" always is 0.
- Try to use SVT-HEVC version v1.3.0 to encode HEVC bitstreams with parameter "-vid-info" equals to 0 or 1, then use tools to check generated HEVC bitstreams, the value of "vps_timing_info_present_flag" always is 1.

The encode command line we used as below: (take v1.3.0 app as example)
encoders/SvtHevcEncApp -i Netflix_FoodMarket2_4it_60Hz_P420.yuv  -b bitstreams/M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q35_TUNE0_0_1_0_vid_0.265  treams/M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q35_TUNE0_0_1_0.errlog  -w 4096  -h 2160  -bit-depth  -intra-period 55  -n 20  -compressed-ten-bit-format 0  -q 35  -hierarchical-levels 1  -encMode 9  -rc 0 **_-vid-info 0_**

**Comment by dseah-intel** [comment]
Hi there, "-vid-info" is used to turn on and off the VUI within the bitstream, to change the value of "vps_timing_info_present_flag", we introduced a new token, currently in PR #68 .

**Comment by tianjunwork** [comment]
@liweki Your request is done in PR #68. Please check the new build.
