### ISSUE TITLE
Ask for pipe support 

### ISSUE THREAD

**Issue by tnti** [intel/SVT-HEVC#9]
As title
An example call could be:
ffmpeg.exe -i "%~dpn1.avs" -f rawvideo -an -| ebHevcEncApp.exe -w 1920 -h 1080 -rc 0 -qp 26 -fps-num 24000 -fps-denom 1001 -i - -b "%~dpn1.hevc"

**Comment by tianjunwork** [comment]
@tnti Thx for your feedback. 
Currently, app expects FrameToBeEncoded(-n) if the input is not file. 
Does it ok for you?
You can try pull request (Support reading from pipe) to unblock you.

**Comment by tianjunwork** [comment]
@tnti According to https://ffmpeg.org/ffmpeg-protocols.html#pipe, pipe is supported on *nix system. Using - as a filename to mean stdin/stdout is a convention that a lot of programs use.
The pull request #3 works on Linux and get same error on Windows.
Did you ever get ffmpeg output pipe working on Windows? Could you show me an example?

**Comment by tnti** [comment]
@tianjunwork 
example：
ffmpeg.exe -i "%~dpn1.mp4" -nostdin -f rawvideo -pix_fmt yuv420p - |  ebHevcEncApp.exe -w 1920 -h 1080 -n 100 -i stdin -b "%~dpn1.hevc"
I don't have this error with other encoders on Windows.
FFMPEG is from https://ffmpeg.zeranoe.com/builds/.

**Comment by tianjunwork** [comment]
SVT sample app doesn't follow convention of using - as a filename to mean stdin/stdout.
-i can only be followed by "stdin" or a filename.

**Comment by tnti** [comment]
Using -i stdin is still reporting an error.

ffmpeg.exe -i "%~dpn1.mp4" -nostdin -f rawvideo -pix_fmt yuv420p - | ebHevcEncApp.exe -w 1920 -h 1080 -n 100 -i stdin -b "%~dpn1.hevc"
-------------------------------------
SVT-HEVC Encoder v1.2.0
Platform:   64 bit
Compiler: VS17
APP Build date: Oct 21 2018 21:24:35
LIB Build date: Oct 21 2018 21:24:16
-------------------------------------
Number of cores available: 8
Number of PPCS 90
ffmpeg version N-92202-gf72b9904fe Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 33.101 / 58. 33.101
  libavformat    58. 19.100 / 58. 19.100
  libavdevice    58.  4.105 / 58.  4.105
  libavfilter     7. 33.101 /  7. 33.101
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Encoding          Input #0, avisynth, from 'E:\Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai 03.mkv.avs':
  Duration: 00:25:00.00, start: 0.000000, bitrate: 0 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> rawvideo (native))
Output #0, rawvideo, to 'pipe:':
  Metadata:
    encoder         : Lavf58.19.100
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, q=2-31, 596600 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.33.101 rawvideo
      10034 fps=0.0 q=-0.0 size=  103275kB time=00:00:01.41 bitrate=596600.3kbits/s speed=2.81x
Error encoding at channel 1! Check error log file for more details ...
Encoder finished
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
frame=   44 fps=8.0 q=-0.0 Lsize=  132308kB time=00:00:01.83 bitrate=590611.8kbits/s speed=0.334x
video:133650kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

The encoded code stream has an error.
![](http://wx3.sinaimg.cn/mw690/7979e806gy1fwg676ba1qj219c0t3dix.jpg)

**Comment by tianjunwork** [comment]
I tried with the ffmpeg build you provided https://ffmpeg.zeranoe.com/builds/ (ffmpeg version N-92226-g2797bd5c81). I can't not reproduce the issue of corrupted video. 
Below error doesn't matter. It is reported by ffmpeg when SVT app finish encoding and terminate the pipe.
_av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe_

SVT encoder did report "Error encoding at channel 1! Check error log file for more details ..." Which I've no idea what it is.
To separate the issues, could you just run SVT encoder with a regular yuv file input with the same cmd input?

**Comment by tnti** [comment]
Using the yuv input encoder results everything works fine.
The encoder still reports Error encoding at channel 1.

**Comment by tnti** [comment]
@tianjunwork 
Can be used normally.

**Comment by ahmad-punch** [comment]
**av_interleaved_write_frame(): Invalid argument
Error writing trailer of pipe:: Invalid argument**

Objective: converting an mp4 video to gif with smallest possible size.
Command trying to run: 
 ffmpeg -i SampleInput.mp4  -vf "fps=10,scale=480:-1:flags=lanczos" -c:v pam -f image2pipe - | convert -delay 10 -loop 0 -layers optimize sample1.gif

Another command that i tried that resulted in the same error:
 ffmpeg -i input.mp4  -vf "fps=10,scale=480:-1:flags=lanczos" -c:v pam -f image2pipe - | convert -delay 5 -loop 0 -dither None -colors 80 "frames/ffout*.png" -fuzz "40%" -layers OptimizeFrame "output.gif"

Complete terminal output:
C:\Ahmad\ImageVideoStitch> ffmpeg -i SampleVideos/video1/stackandFullwithAspectRatio.mp4  -vf "fps=10,scale=480:-1:flags=lanczos" -c:v pam -f image2pipe - | convert -delay 10 -loop 0 -layers optimize SampleVideos/video1/sample8_10fps_withConvert.gif
Invalid Parameter - 10
ffmpeg version git-2020-03-03-60b1f85 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray 
--enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.100 / 56. 42.100
  libavcodec     58. 73.102 / 58. 73.102
  libavformat    58. 39.101 / 58. 39.101
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'SampleVideos/video1/stackandFullwithAspectRatio.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.39.101
  Duration: 00:00:36.02, start: 0.000000, bitrate: 2295 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 2162 kb/s, 29.55 fps, 1000k tbr, 1000k tbn, 2000k tbc (default)  
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> pam (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.39.101
    Stream #0:0(und): Video: pam, rgb24, 480x270 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.73.102 pam
av_interleaved_write_frame(): Invalid argument
Error writing trailer of pipe:: Invalid argument
frame=    1 fps=0.0 q=-0.0 Lsize=     380kB time=00:00:00.10 bitrate=31109.0kbits/s speed=0.246x
video:380kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Conversion failed!

**Comment by tianjunwork** [comment]
Hi @ahmad-punch, is this something to do with svt-hevc?

**Comment by ahmad-punch** [comment]
Hi, no... my bad. Just saw the errors were identical and it involved ffmpeg so posted my query here.
Any ways thanks :P.

**Comment by tianjunwork** [comment]
Hi @ahmad-punch, no problem:)
